# GitLeaks configuration for Happy Coder
# Excludes Firebase API keys which are meant to be public in mobile apps

title = "Happy Coder GitLeaks Config"

# Allowlist Firebase API keys and Google Services files
[[allowlist]]
description = "Firebase API Keys (public by design)"
regexes = [
    '''AIza[A-Za-z0-9_-]{35}''',
]

[[allowlist]]
description = "Google Services JSON template placeholders"
regexes = [
    '''YOUR_GOOGLE_API_KEY_HERE''',
    '''YOUR_PROJECT_ID''',
    '''YOUR_PROJECT_NUMBER''',
    '''YOUR_MOBILE_SDK_APP_ID''',
]

[[allowlist]]
description = "Firebase/Google configuration files"
paths = [
    '''google-services\.json$''',
    '''google-services\.json\.template$''',
    '''GoogleService-Info\.plist$''',
]

# Allow common development placeholders
[[allowlist]]
description = "Development placeholders"
regexes = [
    '''your_.*_here''',
    '''YOUR_.*_HERE''',
    '''<your-.*>''',
    '''\{your.*\}''',
]