# GitLeaks configuration for Happy Coder
# Excludes Firebase API keys which are meant to be public in mobile apps

title = "Happy Coder GitLeaks Config"

# Allowlist Firebase API keys, Google Services files, and development placeholders
[allowlist]
description = "Firebase API Keys, development placeholders, and config files"
regexes = [
    '''AIza[A-Za-z0-9_-]{35}''',
    '''YOUR_GOOGLE_API_KEY_HERE''',
    '''YOUR_PROJECT_ID''',
    '''YOUR_PROJECT_NUMBER''',
    '''YOUR_MOBILE_SDK_APP_ID''',
    '''your_.*_here''',
    '''YOUR_.*_HERE''',
    '''<your-.*>''',
    '''\{your.*\}''',
]
paths = [
    '''google-services\.json$''',
    '''google-services\.json\.template$''',
    '''GoogleService-Info\.plist$''',
    '''\.env$''',
    '''\.env\..*$''',
]