apiVersion: apps/v1
kind: Deployment
metadata:
  name: happy-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: happy-app
  template:
    metadata:
      labels:
        app: happy-app
    spec:
      containers:
      - name: happy-app
        image: docker.korshakov.com/happy-app:{version}
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 3
        startupProbe:
          httpGet:
            path: /
            port: 80
          periodSeconds: 10
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: happy-app
spec:
  selector:
    app: happy-app
  ports:
  - port: 3000
    targetPort: 80
  type: ClusterIP