name: Build Desktop App

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # Allow manual triggers

jobs:
  build-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: ubuntu-self-hosted
            os: ubuntu
          - platform: macos-latest
            os: macos
          - platform: windows-latest
            os: windows

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Install dependencies (Ubuntu only)
      if: matrix.os == 'ubuntu'
      run: |
        if [ "${{ matrix.platform }}" != "ubuntu-self-hosted" ]; then
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev libayatana-appindicator3-dev librsvg2-dev
        else
          echo "Dependencies already installed on self-hosted runner"
        fi

    - name: Install dependencies
      run: npm install --legacy-peer-deps

    - name: Build Tauri app
      uses: tauri-apps/tauri-action@v0.5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        projectPath: src-tauri
        tagName: app-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
        releaseName: 'Happy Desktop v__VERSION__'
        releaseBody: 'See the assets to download this version and install.'
        releaseDraft: true
        prerelease: false
        includeDebug: false

    - name: Notify Build Complete
      if: always()
      run: |
        curl -X POST "https://api.postmarkapp.com/email" \
          -H "Accept: application/json" \
          -H "Content-Type: application/json" \
          -H "X-Postmark-Server-Token: ${{ secrets.POSTMARK_SERVER_TOKEN }}" \
          -d '{
            "From": "hello@blueroots.io",
            "To": "jefferson@heimdallstrategy.com",
            "Subject": "🎉 Happy Desktop Build ${{ job.status }} - ${{ matrix.os }}",
            "HtmlBody": "<h2>Happy Desktop Build Completed!</h2><p><strong>Status:</strong> ${{ job.status }}</p><p><strong>Platform:</strong> ${{ matrix.os }}</p><p><strong>Run:</strong> <a href=\"${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}\">View Details</a></p><p>Build artifacts should be available in the draft release.</p>",
            "TextBody": "Happy Desktop build completed!\n\nStatus: ${{ job.status }}\nPlatform: ${{ matrix.os }}\nRun: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}\n\nBuild artifacts should be available in the draft release."
          }'